### ISSUE TITLE
Default Value for a Dictionary should be None

### ISSUE THREAD

**Issue by omarmhaimdat** [mirage-ai-com/python-mirage-api#1]
As dictionaries are passed by reference, this might lead to unexpected behavior

https://github.com/mirage-ai-com/python-mirage-api/blob/3520cc87a91ac36d06e666ebe260d3add974f6dc/mirage_api/__init__.py#L50C52-L50C52

**Comment by valeriansaliou** [comment]
Thank you for this feedback. Could you please elaborate?

**Comment by omarmhaimdat** [comment]
The simplest explanation can be found here:  https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html

TLDR:
> The first time that the function is called, Python creates a persistent object for the list or dictionary. Every subsequent time the function is called, Python uses that same persistent object that was created from the first call to the function.

**Comment by valeriansaliou** [comment]
I understand the issue, however it doesnt seem to apply there, as we do not mutate the data nor the query objects contents by reference. We only re-assign a new local `data` variable, but that doesn't alter the original default object.
